version: '2'
services:
    test-HTTP:
        image: jenkins-network-e2e
        privileged: true
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - /repos/c:/repos/c
        environment:
            - IOTHUB_CONNECTION_STRING
            - IOTHUB_DEVICE_CONN_STR
            - IOTHUB_E2E_X509_CERT
            - IOTHUB_E2E_X509_PRIVATE_KEY
            - IOTHUB_E2E_X509_THUMBPRINT
            - IOTHUB_EVENTHUB_CONNECTION_STRING
            - IOTHUB_PARTITION_COUNT
        command: bash -c "/repos/c/network_e2e/individual_test.sh HTTP"
        networks:
            - default

    test-AMQP:
        image: jenkins-network-e2e
        privileged: true
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - /repos/c:/repos/c
        environment:
            - IOTHUB_CONNECTION_STRING
            - IOTHUB_DEVICE_CONN_STR
            - IOTHUB_E2E_X509_CERT
            - IOTHUB_E2E_X509_PRIVATE_KEY
            - IOTHUB_E2E_X509_THUMBPRINT
            - IOTHUB_EVENTHUB_CONNECTION_STRING
            - IOTHUB_PARTITION_COUNT
        command: bash -c "/repos/c/network_e2e/individual_test.sh AMQP"
        networks:
            - default

    test-AMQP-WS:
        image: jenkins-network-e2e
        privileged: true
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - /repos/c:/repos/c
        environment:
            - IOTHUB_CONNECTION_STRING
            - IOTHUB_DEVICE_CONN_STR
            - IOTHUB_E2E_X509_CERT
            - IOTHUB_E2E_X509_PRIVATE_KEY
            - IOTHUB_E2E_X509_THUMBPRINT
            - IOTHUB_EVENTHUB_CONNECTION_STRING
            - IOTHUB_PARTITION_COUNT
        command: bash -c "/repos/c/network_e2e/individual_test.sh AMQP-WS"
        networks:
            - default

    test-MQTT:
        image: jenkins-network-e2e
        privileged: true
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - /repos/c:/repos/c
        environment:
            - IOTHUB_CONNECTION_STRING
            - IOTHUB_DEVICE_CONN_STR
            - IOTHUB_E2E_X509_CERT
            - IOTHUB_E2E_X509_PRIVATE_KEY
            - IOTHUB_E2E_X509_THUMBPRINT
            - IOTHUB_EVENTHUB_CONNECTION_STRING
            - IOTHUB_PARTITION_COUNT
        command: bash -c "/repos/c/network_e2e/individual_test.sh MQTT"
        networks:
            - default

    test-MQTT-WS:
        image: jenkins-network-e2e
        privileged: true
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
            - /repos/c:/repos/c
        environment:
            - IOTHUB_CONNECTION_STRING
            - IOTHUB_DEVICE_CONN_STR
            - IOTHUB_E2E_X509_CERT
            - IOTHUB_E2E_X509_PRIVATE_KEY
            - IOTHUB_E2E_X509_THUMBPRINT
            - IOTHUB_EVENTHUB_CONNECTION_STRING
            - IOTHUB_PARTITION_COUNT
        command: bash -c "/repos/c/network_e2e/individual_test.sh MQTT-WS"
        networks:
            - default

networks:
    default:
        external:
            name: YoYoNet

